// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package com.kirshi.protocol;

public final class CmdProto {
  private CmdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.kirshi.protocol.CmdAction}
   */
  public enum CmdAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TK_ACTION_HANDSHAKE = 0;</code>
     */
    TK_ACTION_HANDSHAKE(0),
    /**
     * <code>TK_ACTION_KICK = 1;</code>
     */
    TK_ACTION_KICK(1),
    /**
     * <code>TK_ACTION_RESTART_SERVER = 2;</code>
     */
    TK_ACTION_RESTART_SERVER(2),
    /**
     * <code>TK_ACTION_HEARTBEAT = 3;</code>
     */
    TK_ACTION_HEARTBEAT(3),
    /**
     * <code>TK_ACTION_COMMAND = 4;</code>
     */
    TK_ACTION_COMMAND(4),
    /**
     * <code>TK_ACTION_COMMAND_RESULT = 5;</code>
     */
    TK_ACTION_COMMAND_RESULT(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TK_ACTION_HANDSHAKE = 0;</code>
     */
    public static final int TK_ACTION_HANDSHAKE_VALUE = 0;
    /**
     * <code>TK_ACTION_KICK = 1;</code>
     */
    public static final int TK_ACTION_KICK_VALUE = 1;
    /**
     * <code>TK_ACTION_RESTART_SERVER = 2;</code>
     */
    public static final int TK_ACTION_RESTART_SERVER_VALUE = 2;
    /**
     * <code>TK_ACTION_HEARTBEAT = 3;</code>
     */
    public static final int TK_ACTION_HEARTBEAT_VALUE = 3;
    /**
     * <code>TK_ACTION_COMMAND = 4;</code>
     */
    public static final int TK_ACTION_COMMAND_VALUE = 4;
    /**
     * <code>TK_ACTION_COMMAND_RESULT = 5;</code>
     */
    public static final int TK_ACTION_COMMAND_RESULT_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CmdAction valueOf(int value) {
      return forNumber(value);
    }

    public static CmdAction forNumber(int value) {
      switch (value) {
        case 0: return TK_ACTION_HANDSHAKE;
        case 1: return TK_ACTION_KICK;
        case 2: return TK_ACTION_RESTART_SERVER;
        case 3: return TK_ACTION_HEARTBEAT;
        case 4: return TK_ACTION_COMMAND;
        case 5: return TK_ACTION_COMMAND_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CmdAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdAction>() {
            public CmdAction findValueByNumber(int number) {
              return CmdAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kirshi.protocol.CmdProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CmdAction[] VALUES = values();

    public static CmdAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CmdAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kirshi.protocol.CmdAction)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tCmd.proto\022\023com.kirshi.protocol*\244\001\n\tCmd" +
      "Action\022\027\n\023TK_ACTION_HANDSHAKE\020\000\022\022\n\016TK_AC" +
      "TION_KICK\020\001\022\034\n\030TK_ACTION_RESTART_SERVER\020" +
      "\002\022\027\n\023TK_ACTION_HEARTBEAT\020\003\022\025\n\021TK_ACTION_" +
      "COMMAND\020\004\022\034\n\030TK_ACTION_COMMAND_RESULT\020\005B" +
      "\nB\010CmdProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
