// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pulse.proto

package com.kirshi.protocol;

public final class PulseProto {
  private PulseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PulseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kirshi.protocol.PulseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
     */
    int getCmdValue();
    /**
     * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
     */
    com.kirshi.protocol.CmdProto.CmdAction getCmd();
  }
  /**
   * Protobuf type {@code com.kirshi.protocol.PulseMessage}
   */
  public  static final class PulseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kirshi.protocol.PulseMessage)
      PulseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PulseMessage.newBuilder() to construct.
    private PulseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PulseMessage() {
      cmd_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PulseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kirshi.protocol.PulseProto.internal_static_com_kirshi_protocol_PulseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kirshi.protocol.PulseProto.internal_static_com_kirshi_protocol_PulseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kirshi.protocol.PulseProto.PulseMessage.class, com.kirshi.protocol.PulseProto.PulseMessage.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
     */
    public com.kirshi.protocol.CmdProto.CmdAction getCmd() {
      com.kirshi.protocol.CmdProto.CmdAction result = com.kirshi.protocol.CmdProto.CmdAction.valueOf(cmd_);
      return result == null ? com.kirshi.protocol.CmdProto.CmdAction.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != com.kirshi.protocol.CmdProto.CmdAction.TK_ACTION_HANDSHAKE.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != com.kirshi.protocol.CmdProto.CmdAction.TK_ACTION_HANDSHAKE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kirshi.protocol.PulseProto.PulseMessage)) {
        return super.equals(obj);
      }
      com.kirshi.protocol.PulseProto.PulseMessage other = (com.kirshi.protocol.PulseProto.PulseMessage) obj;

      boolean result = true;
      result = result && cmd_ == other.cmd_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kirshi.protocol.PulseProto.PulseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kirshi.protocol.PulseProto.PulseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kirshi.protocol.PulseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kirshi.protocol.PulseMessage)
        com.kirshi.protocol.PulseProto.PulseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kirshi.protocol.PulseProto.internal_static_com_kirshi_protocol_PulseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kirshi.protocol.PulseProto.internal_static_com_kirshi_protocol_PulseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kirshi.protocol.PulseProto.PulseMessage.class, com.kirshi.protocol.PulseProto.PulseMessage.Builder.class);
      }

      // Construct using com.kirshi.protocol.PulseProto.PulseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kirshi.protocol.PulseProto.internal_static_com_kirshi_protocol_PulseMessage_descriptor;
      }

      public com.kirshi.protocol.PulseProto.PulseMessage getDefaultInstanceForType() {
        return com.kirshi.protocol.PulseProto.PulseMessage.getDefaultInstance();
      }

      public com.kirshi.protocol.PulseProto.PulseMessage build() {
        com.kirshi.protocol.PulseProto.PulseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kirshi.protocol.PulseProto.PulseMessage buildPartial() {
        com.kirshi.protocol.PulseProto.PulseMessage result = new com.kirshi.protocol.PulseProto.PulseMessage(this);
        result.cmd_ = cmd_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kirshi.protocol.PulseProto.PulseMessage) {
          return mergeFrom((com.kirshi.protocol.PulseProto.PulseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kirshi.protocol.PulseProto.PulseMessage other) {
        if (other == com.kirshi.protocol.PulseProto.PulseMessage.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kirshi.protocol.PulseProto.PulseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kirshi.protocol.PulseProto.PulseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
       */
      public com.kirshi.protocol.CmdProto.CmdAction getCmd() {
        com.kirshi.protocol.CmdProto.CmdAction result = com.kirshi.protocol.CmdProto.CmdAction.valueOf(cmd_);
        return result == null ? com.kirshi.protocol.CmdProto.CmdAction.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
       */
      public Builder setCmd(com.kirshi.protocol.CmdProto.CmdAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.kirshi.protocol.CmdAction cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kirshi.protocol.PulseMessage)
    }

    // @@protoc_insertion_point(class_scope:com.kirshi.protocol.PulseMessage)
    private static final com.kirshi.protocol.PulseProto.PulseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kirshi.protocol.PulseProto.PulseMessage();
    }

    public static com.kirshi.protocol.PulseProto.PulseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PulseMessage>
        PARSER = new com.google.protobuf.AbstractParser<PulseMessage>() {
      public PulseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PulseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PulseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PulseMessage> getParserForType() {
      return PARSER;
    }

    public com.kirshi.protocol.PulseProto.PulseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kirshi_protocol_PulseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kirshi_protocol_PulseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Pulse.proto\022\023com.kirshi.protocol\032\tCmd." +
      "proto\032\031google/protobuf/any.proto\";\n\014Puls" +
      "eMessage\022+\n\003cmd\030\001 \001(\0162\036.com.kirshi.proto" +
      "col.CmdActionB\014B\nPulseProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kirshi.protocol.CmdProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_kirshi_protocol_PulseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kirshi_protocol_PulseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kirshi_protocol_PulseMessage_descriptor,
        new String[] { "Cmd", });
    com.kirshi.protocol.CmdProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
